let list = [
    "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
    "Difficult roads often lead to beautiful destinations.",
    "Stop hating yourself for everything you aren’t and start loving yourself for everything you already are.",
    "Be somebody nobody thought you had the strength to be.",
    "Tough times don’t last. Tough people do.",
    "You will never have this day again. Make it count.",
    "No matter how you feel, get up, dress up, show up and never give up.",
    "A river cuts through rock, not because of its power, but because of its persistence.",
    "Don’t stop when you are tired, stop when you are done.",
    "Do one thing every day that challenges you.",
    "The pessimist sees difficulty in every opportunity. The optimist sees the opportunity in every difficulty.",
    "A little progress each day adds up to big results.",
    "It won't be easy but it will be worth it.",
    "You don’t have to see the whole staircase, just take the first step.",
    "If it doesn’t challenge you it wont change you.",
    "Stop being afraid of what could go wrong and think of what could go right.",
    "Be stubborn about your goals and flexible about your methods.",
    "The key to success is to focus our conscious mind on the things we desire, not the things we fear.",
    "Never assume that you’re stuck with the way things are right now. You aren’t. Life changes every single moment, and so can you.",
    "Life is inherently risky. There is only one big risk you should avoid at all costs, and that is the risk of doing nothing.",
    "Push harder than yesterday if you want a different tomorrow.",
    "Your only limit is you.",
    "You only fail when you stop trying.",
    "If the plan doesn’t work, change the plan but never the goal.",
    "If you stumble, get back up. What happened yesterday no longer matters. Today is a new day, so move closer to your dreams.",
    "The difference between who you are and who you want to be is what you do.",
    "You are capable of more than you know.",
    "Nothing changes if nothing changes.",
    "The man on top of the mountain didn’t fall there.",
    "Do what you have to do until you can do what you want to do.",
    "The harder you work for something the greater you feel when you achieve it.",
    "Be stronger than your excuses.",
    "It doesn’t matter how slowly you go as long as you do not stop.",
    "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
    "It’s not about perfect. It's about effort. When you implement effort into your life every day, that’s where transformation happens.",
    "You are braver than you believe, stronger than you seem and smarter than you think.",
    "Sometimes what you’re most afraid of doing is the very thing that will set you free.",
    "Respect yourself enough to say ‘I deserve happiness’ and walk away from anything that prevents you from attaining it.",
    "Your life only gets better when you work on yourself and the rest will follow.",
    "There are two ways to be happy- change the situation, or change your mindset.",
    "A negative mind will never give you a positive life.",
    "You will never change your life until you change something you do daily. The secret of your success is found in your daily routine.",
    "At any given moment you have the power to say - ‘This is not how the story is going to end’.",
    "We must all face the choice between what is right and what is easy.",
    "To have what you have never had, you have to do what you have never done.",
    "Don’t feel sorry for yourself if you have chosen the wrong road. Turn around.",
    "Discipline is choosing between what you want now and what you want most.",
    "Stay positive, work hard and make it happen.",
    "Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.",
    "Wake up with determination. Go to bed with satisfaction.",
    "In any given moment we have two options: to step forward into growth or step backward into regret.",
    "I’m thankful for my struggle because without it I would not have stumbled upon my strength.",
    "Everything you do today you do for your future. Think about that.",
    "Be thankful for what you are now, and keep fighting for what you want to be tomorrow.",
    "Attract what you expect, reflect what you desire, become what you respect, mirror what you admire.",
    "The only limits in your life are the ones that you create.",
    "Everything you need, your courage, strength, compassion and love; everything you need is already within you.",
    "A comfort zone is a wonderful place but nothing ever grows there.",
    "Soon, when all is well, you are going to look back on this period of your life and be glad that you never gave up.",
    "You are capable of more than you know.",
    "If its important to you, you will find a way.",
    "One reason people resist change is because they focus on what they have to give up, instead of what they have to change.",
    "If you don’t go after what you want, you’ll never have it.",
    "If you don’t step forward you’re always in the same place.",
    "Push harder than yesterday if you want a new tomorrow.",
    "Be strong enough to stand alone, smart enough to know when you need help, and brave enough to ask for it.",
    "There comes a time when you have to choose between turning the page and closing the book.",
    "Don’t let how you feel make you forget what you deserve.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.",
    "Our greatest glory is not in never failing, but in rising every time we fail.",
    "The only person you are destined to become is the person you decide to be.",
    "The first step towards getting somewhere is to decide that you are not going to stay where you are.",
    "Everyday may not be good, but there is something good in everyday.",
    "Strength does not come from winning. Strength comes from struggle. When you survive hardships without surrender, that is strength.",
    "All our dreams can come true if we have the courage to pursue them.",
    "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.",
    "Success is the sum of small efforts, repeated day-in and day-out.",
    "Strength and growth come only through continuous effort and struggle.",
    "The first step toward success happens when you refuse to be a captive of the situation in which you find yourself.",
    "Don’t let what you cannot do interfere with what you can do.",
    "You may have to fight a battle more than once to win it.",
    "A man can be as great as he wants to be if you believe in yourself and have the courage to get it done.",
    "Every great story on the planet happened when someone decided not to give up, but kept going no matter what.",
    "Failure will never overtake you if your determination to succeed is strong enough.",
    "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit.",
    "Action is the foundational key to all success.",
    "Successful people do what unsuccessful people are not willing to do.",
    "That which does not kill us makes us stronger.",
    "Don’t wish it were easier, wish you were better.",
    "The question isn’t who is going to let me; it’s who is going to stop me.",
    "Little minds are tamed and subdued by misfortune; but great minds rise above it.",
    "You don’t have to be great to start, but you have to start to be great.",
    "The will to win, the desire to succeed, the urge to reach your full potential- these are the keys to unlocking personal excellence.",
    "Things work out best for those who make the best of how things work out.",
    "Perfection is not attainable, but if we chase perfection we can catch excellence.",
    "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.",
    "Opportunities don’t happen, you create them.",
    "The secret of getting ahead is getting started.",
    "The secret of getting ahead is getting started.",
    "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
    "Two types of people tell you that you cannot make a difference. Those who are afraid to try and those who are afraid you will succeed.",
    "What’s the point of being alive if you don’t at least try to do something remarkable.",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.",
    "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
    "Too many of us are not living our dreams because we are living our fears.",
    "Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "The starting point of all achievement is desire.",
    "You can never cross the ocean unless you have the courage to lose sight of the shore.",
    "There are two primary choices in life; to accept conditions as they exist, or to accept the responsibility for changing them.",
    "Whatever the mind can conceive and believe, it can achieve.",
    "You miss 100% of the shots you don’t take.",
    "The most difficult thing is the decision to act, the rest is merely tenacity.",
    "Every strike brings me closer to the next home run.",
    "We become what we think about, so think big, think bright, think happiness.",
    "The most common way people give up their power is by thinking they don’t have any.",
    "Either you run the day, or the day runs you.",
    "Life shrinks or expands in proportion to one's courage.",
    "Good, better, best. Never let it rest. Until your good is better and your better is best.",
    "Infuse your life with action. Don’t wait for it to happen. Make it happen. Make your own future.",
    "With every new day comes new strength and new thoughts.",
    "In order to succeed, you must first believe that you can.",
    "Always do your best. What you plant now you will harvest later.",
    "Believe in yourself and have faith in your abilities. With a humble confidence in your own abilities your success is inevitable",
    "If you can dream it. You can do it.",
    "We should not give up and we should not allow the past to defeat us.",
    "What you do today can improve your tomorrows",
    "There is only one corner of the universe you can be certain of improving, and that is your own self.",
    "Start where you are. Use what you have. Do what you can.",
    "Change your life today. Don’t gamble on the future, act now, without delay.",
    "We may encounter many defeats but we must not be defeated.",
    "Consult not your fears but your hopes and dreams.",
    "Think not about your frustrations, but your unfulfilled potential.",
    "Never, ever, ever give up.",
    "Only I can change my life. No one can do it for me.",
    "Set your goals high, and don’t stop till you get there.",
    "Without hard work, nothing grows but weeds.",
    "The past cannot be changed. The future is yet in your power.",
    "Perseverance is falling down seven times but getting up eight.",
    "Never give in and never give up.",
    "We make the world we live in and shape our environment.",
    "A somebody was once a nobody who wanted to and did.",
    "Decide what you want, decide what you are willing to exchange for it. Establish your priorities and go to work.",
    "The more things you do the more things you can do.",
    "Do not wait- the time will never be ‘just right’.",
    "Don’t fight the problem. Resolve it.",
    "Do the things you think you can’t do.",
    "Learn from the past, set goals for the future, and live in the only moment of time over which you have any control. Now.",
    "I can, therefore I am.",
    "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.",
    "Strength and growth come only through continuous effort and struggle.",
    "Strength comes from indomitable will.",
    "Be faithful in small things because it is in them that strength lies.",
    "That which does not kill us makes us stronger.",
    "Great works are performed not by strength but by perseverance.",
    "Endurance is not just the ability to bear a hard thing, but to turn it into glory.",
    "Where there is no struggle there is no strength.",
    "As long as we persevere and endure, we can get anything we want.",
    "Mastering others is strength. Mastering yourself is true power.",
    "Once you replace negative thoughts with positive ones, you’ll start having positive results.",
    "You cannot have a positive life and a negative mind.",
    "Live life to the fullest, and focus on the positive.",
    "Adopting the right attitude can convert a negative stress into a positive one.",
    "In order to carry a positive action we must develop a positive vision.",
    "Everyday brings new choices.",
    "Believe that life is worth living and your belief will help create the fact.",
    "Virtually nothing is impossible in this world if you just put your mind to it and maintain a positive attitude.",
    "If you don’t like something change it. If you can’t change it change your attitude.",
    "Change your thoughts and you change your world.",
    "Without a struggle there can be no progress.",
    "You must be the change you wish to see in the world.",
    "You cannot change your destination overnight, but you can change your direction overnight.",
    "Failure is not fatal, but failure to change can be.",
    "The first step towards change is awareness. The second step is acceptance.",
    "Change brings opportunity.",
    "We cannot change anything until we accept it.",
    "You must do the things you think you can not do.",
    "The best preparation for tomorrow is doing your best today.",
    "Put your heart, mind and soul into even your smallest acts. This is the secret of success.",
    "What we think, we become.",
    "It is in your moments of decision that your destiny is shaped.",
    "Start by doing what’s necessary; then do what’s possible; and suddenly you are doing the impossible.",
    "Turn your face to the sun and the shadows will be behind you.",
    "It is never to late to be what you might have been.",
    "With self-discipline anything is possible.",
    "We can change our lives. We can do, have, and be exactly what we wish.",
    "There is nothing impossible to those who try.",
    "Everything you want is out there waiting for you. Everything you want also wants you. But you have to take action to get it.",
    "What we achieve inwardly will change outer reality.",
    "The limits of the possible can only be defined by going beyond them into the impossible.",
    "Find out who you are and be that person. Find that truth, live that truth and everything else will come.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "Courage my friends; ‘tis not to late to build a better world’.",
    "Reach for it. Push yourself as far as you can.",
    "Out of difficulties grow miracles.",
    "Each day provides its own gifts.",
    "Let us make our future now, and let us make our dreams tomorrow's reality.",
    "If you want to be happy, do not dwell on the past, do not worry about the future, focus on living fully in the present.",
    "Life is really simple. Don’t insist on making it complicated.",
    "In the end, its not the years in your life that counts. It’s the life in your years.",
    "There are two great days in a persons life- the day we are born and the day we discover why.",
    "However difficult life may seem, there is always something you can do to succeed at it.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Very little is needed to make a happy life; it is all within your self, in your way of thinking.",
    "Opportunities to find deeper powers within ourselves come when life seems most challenging.",
    "Everyone is handed adversities in life. No ones journey is easy. It’s how they handle it that make people unique.",
    "It takes half your life before you discover life is a do-it-yourself project.",
    "Life doesn’t require that we be the best, only that we try our best.",
    "We first make our habits then our habits make us.",
    "I have not failed, I have just found one thousand ways that won’t work.",
    "Success is not final, failure is not fatal; it is the courage to continue that counts.",
    "Happiness is not something ready made. It comes from your own actions.",
    "You never fail until you stop trying.",
    "Though nobody can go back and make a new beginning, anyone can start over and make a new ending",
    "Anyone can hide. Facing up to things, working through them, that’s what makes you strong.",
    "To change your life, change your habits.",
    "Thinking something does not make it true. Wanting something does not make it real.",
    "No matter what happens, or how bad it seems today, life does go on, and it will be better tomorrow.",
    "Bad habits are easier abandoned today than tomorrow.",
    "It’s only after you’ve stepped outside your comfort zone that you begin to change, grow, and transform.",
    "You must give everything to make your life as beautiful as the dreams that dance in your imagination.",
    "The more you feed your mind with positive thoughts, the more you can attract great things into your life.",
    "You leave old habits behind by starting out with the thought ‘I release the need for this in my life’.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You never change your life until you step out of your comfort zone; change begins at the end of your comfort zone.",
    "Hard times lead to great times.",
    "If you want to fly, you have to give up what weighs you down.",
    "The past is a place of learning, not a place of living.",
    "When the going gets tough, put one foot in front of the other and just keep going.",
    "The secret to permanently breaking any bad habit is to love something greater than the habit.",
    "It's time to start living the life you've imagined.",
    "Life is about accepting the challenges along the way, choosing to keep moving forward, and savouring the journey.",
    "Maturity is when you stop complaining and making excuses, and start making changes.",
    "Don’t make a habit of choosing what makes you feel good over what's actually good for you.",
    "It’s okay to look back to see how far you’ve come but keep moving forward.",
    "No amount of regretting can change the past, and no amount of worrying can change the future.",
    "Once you realize you deserve a bright future, letting go of your dark past is the best choice you will ever make.",
    "Bad habits are our enemies because they hinder us from being the person we want to be.",
    "The most empowering thing in life is when you come to the realization that the only thing that can save you is yourself.",
    "Focus on your strengths, not your weaknesses.Focus on your character, not your reputation.Focus on your blessings, not your misfortunes.",
    "Believe in your infinite potential. Your only limitations are those you set upon yourself.",
    "The surest way to make your dreams come true is to live them.",
    "It takes guts and humility to admit mistakes. Admitting we're wrong is courage, not weakness.",
    "Dreams don't work unless you take action. The surest way to make your dreams come true is to live them.",
    "You cannot change your future. But you can change your habits. And surely your habits will change your future.",
    "Stop doing what is easy. Start doing what is right.",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine",
    "Happiness depends on your mindset and attitude.",
    "Don’t wait for things to happen. Make them happen.",
    "First we form habits, then they form us. Conquer your bad habits, or they will eventually form you.",
    "Never lose hope. Storms make people stronger and never last forever.",
    "Do not fear failure but rather fear not trying.",
    "Turn your obstacles into opportunities and your problems into possibilities.",
    "A man who can’t bear to share his habits is a man who needs to quit them.",
    "Make the most of the best and the best of the worst, and keep your standards high. Never settle for anything less than you deserve.",
    "The level of success you achieve will be in direct proportion to the depth of your commitment.",
    "Create a vision for the life you really want and then work relentlessly towards making it a reality.",
    "When you take control of your attitude, you take control of your life.",
    "The difference between the impossible and the possible lies in a person's determination.",
    "The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, you cannot move forward.",
    "The only way of discovering the limits of the possible is to venture a little way past them into the impossible.",
    "Happiness is not the absence of problems, it's the ability to deal with them.",
    "The man who moves a mountain begins by moving small stones.",
    "Change the way you look at things and the things you look at change.",
    "You are not your mistakes. You are not your struggles. You are here now with the power to shape your day and your future.",
    "Do not let the memories of your past limit the potential of your future. There are no limits to what you can achieve on your journey through life.",
    "You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously.",
    "You are essentially who you create yourself to be and all that occurs in your life is the result of your own making.",
    "It doesn’t matter how many times you get knocked down. All that matters is you get up one more time than you were knocked down.",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
    "In order to succeed, your desire for success should be greater than your fear of failure.",
    "My past has not defined me, destroyed me, deterred me, or defeated me; it has only strengthened me.",
    "Success is measured not by the position that one has reached in life but rather by the obstacles which he have been overcome.",
    "The universe doesn’t give you what you ask for with your thoughts - it gives you what you demand with your actions.",
    "The biggest wall you have to climb is the one you build in your mind: Never let your mind talk you out of your dreams.",
    "You must expect great things of yourself before you can do them.",
    "The future belongs to those who prepare for it today.",
    "Live the way you want to be remembered.",
    "Every new day is another chance to change tomorrow.",
    "Out of suffering emerges the strongest souls. The largest characters are forged by scars.",
    "In the end, we only regret the chances we didn’t take.",
    "Life’s longest mile is the stretch from dependence to independence.",
    "You cannot dream yourself into a character. You must hammer and forge yourself into one.",
    "If you conquer your mind, the rest of your life will fall into place.",
    "Good things come to those who work their asses off and never give up.",
    "Nothing splendid has ever been achieved except by those who dared. Believe something inside of them was superior to circumstance.",
    "There is no passion to be found in settling for a life that is less than the one you are capable of living.",
    "One day your life will flash before your eyes. Make sure it’s worth watching.",
    "Ask yourself if what you are doing today is getting you closer to where you want to be tomorrow.",
    "Life begins at the end of your comfort zone.",
    "The important thing is this: to be willing at any moment to sacrifice who you are for who you could become.",
    "Self respect is the root of discipline. Your sense of discipline grows with your ability to say no to oneself.",
    "When you feel like quitting, remember why you started.",
    "Do something today that your future self will thank you for.",
    "Strength doesn’t come from physical strength. It comes from indomitable will.",
    "Energy and persistence conquer all things.",
    "I am not what has happened to me. I am what I choose to become.",
    "A year from now you will be thankful that you started today.",
    "You are the creator of your own destiny.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "Fall seven times and stand up eight.",
    "When you let go of who you are you become who you might be.",
    "If you do what you have always done, you will get what you have always gotten.",
    "You may be disappointed if you fail. But you are doomed if you don’t try.",
    "We are a product of the choices we make. Not the circumstances we face.",
    "The battles that count are the invisible battles inside of us.",
    "Life is a story. Make yourself a best-seller.",
    "Strength shows not only in the ability to persist, but in the ability to start over.",
    "Smile and let the world know that today, you’re a lot stronger than you were yesterday.",
    "Always remember. You are stronger than you think.",
    "The struggle today creates the strength you’ll need for tomorrow.",
    "The strongest people are not those who show strength in front of us but those who win battles we know nothing about.",
    "Life is like a coin. You can only spend it once.",
    "We only live once, but if you do it right once is enough.",
    "If you focus on results, you will never change. If you focus on change, you will get results.",
    "Willpower is the art of replacing one habit for another.",
    "Good character is not given, but built. Hour by hour, piece by piece.",
    "Never give up. Today can be the place and time that the tide will turn.",
    "The only path to happiness is to cease worrying about things beyond our power of control.",
    "Nobody is wise by birth. Wisdom results from ones’ own efforts.",
    "The river beats the rock. Not by strength but by perseverance.",
    "The art of love is largely the art of persistence.",
    "Resilience and strength come only from having the chance to work through difficult problems.",
    "The real glory is being knocked to your knees and then coming back. That’s real glory.",
    "Courage does not always roar. Sometimes it’s a quiet voice saying ‘I will try again tomorrow’.",
    "We are made to persist. That is the only way we know who we are.",
    "Change is hardest in the beginning, messiest in the middle, and best at the end.",
    "Do it badly, do it slowly, do it fearfully. Do it anyway you have to, but do it.",
    "To persist with a goal, you must treasure the dream more than the cost to attain it.",
    "As long as there is breath in you - persist.",
    "We only become failures in life when we give up and stop trying. If you fail, get up and try again.",
    "Losers quit when they fail. Winners fail until they succeed.",
    "Don’t allow your wounds to transform you into someone you are not.",
    "If ever there was a time to do something that matters, it is now.",
    "You are confined only to the walls you build yourself.",
    "Happiness only depends on what happens inside you.",
    "There is no elevator to success. You have to take the stairs.",
    "The walls we build to keep out sadness also keep out joy.",
    "Your life is your message to the world. Make it glorious.",
    "Nothing is more honorable than a courageous heart.",
    "If opportunity doesn’t come knocking. Build a door.",
    "Set a goal so big you cant achieve it until you grow into the kind of person who can.",
    "The future is created by what you decide to do today.",
    "Falling down is how we grow. Staying down is how we fail.",
    "The things we take for granted, someone else is praying for.",
    "The time to be happy is now.",
    "To give anything other than your best is to waste who you are.",
    "It’s a great day to turn your life around.",
    "There are no shortcuts to any place worth going.",
    "For every dark night, there is a brighter day.",
    "No matter how wrong you have gone, you can always turn around.",
    "Be someone who acts and leave the talking to others.",
    "The difference between dreams and thoughts is called action.",
    "The few who do are the envy of the many who watch.",
    "Your actions show what your heart is made of.",
    "Become the person tomorrow needs.",
    "Don’t accept apologies from yourself, only positive action.",
    "The important thing is this - to be ready atany moment to sacrifice who you are for who you could become.",
    "With self-discipline anything is possible.",
    "If you don’t step forward you’re always in the same place.",
    "Don’t make a habit of choosing what makes you feel good over what's actually good for you.",
    "Strength doesn’t come from physical strength. It comes from indomitable will.",
    "Little minds are tamed and subdued by misfortune; but great minds rise above it.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us."
];
export default list;